### ISSUE TITLE
One URL for all Adafruit boards

### ISSUE THREAD

**Issue by don** [adafruit/arduino-board-index#1]
It would be nice to have one URL for all Adafruit boards for easier IDE configuration.

https://apt.adafruit.com/proxy_files/package_adafruit_index.json works for now, but isn't on the [list of 3rd party boards](https://github.com/arduino/Arduino/wiki/Unofficial-list-of-3rd-party-boards-support-urls).

**Comment by toddtreece** [comment]
fixed by 9102d17ae3e3867f8da0a69ceb6ba68fb5da4d51 and added the new URL to the list of 3rd party boards.
