### ISSUE TITLE
SAMD boards: REG_SERCOM?_*_DATA has wrong data width

### ISSUE THREAD

**Issue by WolfWings** [adafruit/arduino-board-index#10]
REG_SERCOM0_SPI_DATA for example is listed as...

    (*(RwReg  *)...

...but the data sheet (across all SERCOM modes, but on page 532 of the AdaFruit-hosted datasheet PDF, section 27.8.10 in this example) lists the register is 16-bit, so the declaration should be...

    (*(RwReg16*)...

...for all the various REG_SERCOM?_*_DATA register declarations.

**Comment by ladyada** [comment]
hiya do you mean to open this in https://github.com/arduino/ArduinoCore-samd ? we dont have any code definitions in thie repo :)

**Comment by WolfWings** [comment]
Is that the repo the adafruit-samd-1.2.1.tar.bz2 archive is built from?

The code definitions in question are inside that archive, but I wasn't able to find where that archive is assembled from.

**Comment by ladyada** [comment]
yes it is the upstream
