### ISSUE TITLE
[v1.4.0] Adafruit Feather nRF52840 Express: Cannot link to `Serial`

### ISSUE THREAD

**Issue by zfields** [adafruit/arduino-board-index#105]
- Arduino board:  **Adafruit Feather nRF52840 Express**

- Arduino IDE version (found in Arduino -> About Arduino menu):  **1.8.19**

- Adafruit nRF52 Boards version: **1.4.0**

- List the steps to reproduce the problem below (if possible attach a sketch or
  copy the sketch code in too): **LIST REPRO STEPS BELOW**

1. Attempt to compile the follow code for the Adafruit Feather nRF52840 Express.

```c++
void setup() {
  // put your setup code here, to run once:
  Serial.begin(115200);
  while (!Serial);
}

void loop() {
  // put your main code here, to run repeatedly:
  Serial.println("Hello, World!");
  delay(5000);
}
```

_I have also tried downgrading to v1.3.0, but that did NOT make a difference._

**Comment by hathach** [comment]
just add `#include "Adafruit_TinyUSB.h"` would solve this. Btw, this issue should be reported in the Adafruit_nRF52_Arduino repo instead
