### ISSUE TITLE
Missing avrdude.conf from AVR Boards package

### ISSUE THREAD

**Issue by per1234** [adafruit/arduino-board-index#3]
avrdude.conf has been missing since AVR Boards 1.1.0 which causes
`avrdude: can't open config file "C:\Users\per\AppData\Local\Arduino15\packages\adafruit\hardware\avr\1.3.0/avrdude.conf": No such file or directory` error when you try to Burn Bootloader.

**Comment by toddtreece** [comment]
@per1234 give 1.3.2 a try. i just pushed this update: e6a4f7e56269b7d416240628a0d7e04f74a3330a

**Comment by per1234** [comment]
Works for me, thanks!
