### ISSUE TITLE
You can't reference bootloader files from another core

### ISSUE THREAD

**Issue by per1234** [adafruit/arduino-board-index#4]
`metro.bootloader.file=arduino:optiboot/optiboot_atmega328.hex` etc. doesn't work, I know it should work and there is even an issue(https://github.com/arduino/Arduino/issues/2656) requesting this functionality for the Arduino IDE, but it doesn't work:
`avrdude: can't open input file C:\Users\per\AppData\Roaming\Arduino15\packages\adafruit\hardware\avr\1.3.0/bootloaders/arduino:optiboot/optiboot_atmega328.hex: Invalid argument`
You have to include your own copies of all these bootloaders.

**Comment by ladyada** [comment]
ah, its identical to the UNO bootloader so just select that when you burn bootloader :)

**Comment by per1234** [comment]
I understand that the board entry is identical to UNO. I'm guessing that the reason for having the entry is so that you don't have to explain to your customers to use the UNO board entry for their Metro board but if you're providing a partially broken boards.txt then you're actually doing them a disservice.Why not make the tiny extra effort to make them work fully? Well it's up to you, I don't even own any of these boards(though I have bought many other items from Adafruit). I just noticed the issue and thought you would appreciate me bringing it to your attention. I won't bother to do so in the future with any Adafruit code. The funny thing is I was using this package for testing purposes because I assumed yours would have the best chance of being completely correct out of any of the 3rd party hardware files.

**Comment by ladyada** [comment]
hiya - reopening this issue - we replied to you within a few hours with a fix so you can continue hacking

**Comment by per1234** [comment]
Sorry, I misunderstood your comment. Thanks for explaining.

**Comment by per1234** [comment]
Fixed via https://github.com/adafruit/arduino-board-index/commit/c8f0811db3c999970e7a64e1cde666e29eed5949 but **Burn Bootloader** still fails because of https://github.com/adafruit/arduino-board-index/issues/3
